name: Playwright Test Pipeline
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{fromJson('["ubuntu-latest","self-hosted"]')[github.repository == 'github/docs-internal']}}

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.x'

        - name: Cache Node Modules
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-

        - name: Install dependencies
          run: npm install

        - name: Install Playwright Browsers
          run: npx playwright install

        - name: Install http-server
          run: npm install -g http-server

        - name: Start http-server
          run: |
                nohup http-server -p 5500 &
        
        - name: Wait for server to start
          run: |
            while !curl -s http://127.0.0.1:5500; do
                echo "Waiting for server to start..."
                sleep 1
            done

        - name: Run Playwright tests
          run: npx playwright test tests/tests-udemy-vapa/auth2.spec.js

          #Ading reporting related steps
        - name: Upload Playwright Report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: playwright-report
            path: playwright-report

        - name: Upload Playwright Videos
          uses: actions/upload-artifact@v4
          if: always()
          with:
           name: videos
           path: test-results/**/*.webm

        - name: Upload Playwright Traces
          uses: actions/upload-artifact@v4
          if: always()
          with:
           name: traces
           path: test-results/**/*.zip

        - name: Upload Playwright Screenshots
          uses: actions/upload-artifact@v4
          if: always()
          with:
           name: screenshots
           path: test-results/**/*.png